import type { Metadata } from "next";
import { Geist, Geist_Mono, Schibsted_Grotesk } from "next/font/google";
// import "./globals.css";
import Link from "next/link";
import { SiWhatsapp } from "react-icons/si";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});
const grotesk = Schibsted_Grotesk({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            {children}
            <div className="flex flex-col sm:flex-row gap-6   fixed bottom-0 right-0 p-6 z-20">

                <Link
                    href={"https://api.whatsapp.com/send?phone=5561984694842&text=Ol%C3%A1%20%2C%20Luiz%20Fellipe%20Joliver!"} target="_blank"
                    className="bg-white/40 rounded-full p-2 group hover:scale-120 duration-300 hidden 2xl:block"
                >
                    <SiWhatsapp className="size-7 group-hover:text-emerald-400  " />
                </Link>
            </div>
        </>
    );
}
